name: nasa_explorer_app
description: A NASA Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  cupertino_icons: ^1.0.2
  logger: ^2.0.2
  shared_preferences: ^2.2.1
  get_it: ^7.0.3
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
